export type Sponsor = {
    name: string,
    location: string,
    image: string,
    link:string
};

export const sponsors: Sponsor[] = [
    {
      name: 'Digitaldruck Fabrik',
      location: 'aus 84109 Wörth a.d. Isar',
      image: 'https://www.digitaldruck-fabrik.de/images/main/logo.png',
      link: 'https://www.digitaldruck-fabrik.de',
    },
    {
      name: 'Band TRIXX',
      location: 'aus 94034 Passau',
      image: 'https://i.ytimg.com/vi/TNYGhFMvlJ8/mqdefault.jpg',
      link: 'https://www.partymat.de/TRIXX',
    },
    {
      name: 'Edeka Leeb',
      location: 'aus 94522 Wallersdorf',
      image: 'https://www.lebensmittel-leeb.de/images/logo.png',
      link: 'https://www.lebensmittel-leeb.de/',
    },
    {
      name: 'Bäckerei Dischinger',
      location: 'aus 94522 Wallersdorf',
      image: 'https://media.cylex.de/companies/7348/716/logo/logo.jpg',
      link: 'https://www.baeckerei-dischinger.de/',
    },
    {
      name: 'Metzgerei Donhauser',
      location: 'aus 94522 Wallersdorf',
      image: 'https://scontent-muc2-1.xx.fbcdn.net/v/t39.30808-6/295073543_584717056387620_23634260024951184_n.png?stp=dst-png_s960x960&_nc_cat=110&ccb=1-7&_nc_sid=52f669&_nc_ohc=3cVeF-DTOLYAX_sfePv&_nc_ht=scontent-muc2-1.xx&oh=00_AfA87TXlAgYAVxFr279Ifczd68SKwp7wmWUQY5PDI6uNqA&oe=6527D80D',
      link: 'https://www.facebook.com/MetzgereiDonhauser/?locale=de_DE',
    },
    {
      name: 'Metzgerei Frisch',
      location: 'aus 94522 Wallersdorf',
      image: 'https://www.metzgerei-frisch.de/wp-content/uploads/frisch-001.png',
      link: 'https://www.metzgerei-frisch.de/',
    },
    {
      name: 'Aster\'s Holunderhof',
      location: 'aus 94522 Ettling',
      image: '/supporter/aster.jpg',
      link: 'https://www.mein-bauernhof.de/verkaufstelle/asters-holunderhof-705559/',
    },
    {
      name: 'Music Station',
      location: 'aus 94330 Aiterhofen',
      image: 'https://www.music-station.de/media/7d/g0/00/1625557432/music-station-logo.png',
      link: 'https://www.music-station.de/',
    },
    {
      name: 'Develey',
      location: 'aus 84130 Dingolfing',
      image: 'https://develey.de/Marken/Brand/Kanaele/brand/logo/develey-logo-brand-marke-markenname.png',
      link: 'https://develey.de/',
    },
    {
      name: 'Ingenieurbüro Peter Weig',
      location: 'aus 94522 Wallersdorf',
      image: 'https://www.weig-online.de/s/misc/logo.jpg?t=1691560016',
      link: 'http://www.weig-online.de/',
    },
    {
      name: 'Eventbar Woibadinga',
      location: 'aus 94522 Wallersdorf',
      image: 'https://eventbar-woibadinga.de/wp-content/uploads/2021/05/Logo.png',
      link: 'https://eventbar-woibadinga.de/',
    },
    {
      name: 'Ziegler Isolierung',
      location: 'aus 94428 Eichendorf',
      image: 'https://image.jimcdn.com/app/cms/image/transf/dimension=216x10000:format=png/path/s4e5bb772c21e79fb/image/i53150231242c47b9/version/1576410612/image.png',
      link: 'https://www.ziegler-isolierungen.de/',
    },
    {
      name: 'Bäckerei Weinzierl',
      location: 'aus 94522 Wallersdorf',
      image: '/supporter/weinzierl.jpg',
      link: 'https://www.wallersdorfer-backhaus.de/',
    },
    {
      name: 'Rechtsanwälte Weiss & Grunert',
      location: 'aus 84028 Landshut',
      image: 'https://www.weiss-grunert.de/wp-content/themes/weissgrunert/img/logo-black.png',
      link: 'https://www.weiss-grunert.de/',
    },
    {
      name: 'Ortmaier Druck',
      location: 'aus 84160 Frontenhausen',
      image: 'https://ortmaier-druck.de/wp-content/uploads/2014/07/ortmaier_header_logo.png',
      link: 'https://ortmaier-druck.de/',
    },
    {
      name: 'TEBA Kreditbank',
      location: 'aus 94405 Landau a. d. Isar',
      image: 'https://www.teba-kreditbank.de/fileadmin/templates/img/TEBA_Logo_2018.svg',
      link: 'https://www.teba-kreditbank.de/',
    },
    {
      name: 'CSU & Frauen Union',
      location: 'aus 94522 Wallersdorf',
      image: 'https://www.csu.de/assets/img/logos/csu-logo-tw.gif',
      link: 'https://www.csu.de/verbaende/ov/wallersdorf/',
    },
    {
      name: 'Fahrschule Eder',
      location: 'aus 94431 Pilsting',
      image: 'https://fahrschule-eder.net/images/page/Eder-FS-logo.png',
      link: 'https://fahrschule-eder.net/',
    },
    {
      name: 'Theatergruppe St. Johannes',
      location: 'aus 94522 Wallersdorf',
      image: 'https://layout.verwaltungsportal.de/1580/img/logo.png',
      link: 'https://wallersdorf.dahoam-in-niederbayern.de/vereine/verein/theatergruppe-st-johannes-991/',
    },
    {
      name: 'Spedition Ast',
      location: 'aus 94522 Wallersdorf',
      image: 'https://sp-ast.de/wp-content/themes/servicepartner/images/logos/sp-ast.jpg',
      link: 'https://sp-ast.de/',
    },
    {
      name: 'Boxclub Wallersdorf',
      location: 'aus 94522 Wallersdorf',
      image: 'https://layout.verwaltungsportal.de/1580/img/logo.png',
      link: 'https://www.markt-wallersdorf.de/verzeichnis/mandat.php?mandat=34059&kategorie=128',
    },
    {
      name: 'Andrea Herzig',
      location: 'aus 93444 Bad Kötzting',
      image: 'https://le-cdn.website-editor.net/s/3b38257c5abf4d51a57e2b0dd0fa8f6e/dms3rep/multi/opt/LOGOHPA-216w.png?Expires=1698627149&Signature=ag5uf5kY3yLbZ-ntUXNHOLO6rPKOxFUPoeK8Ja6WDGWbqjITdRV2Uqyfc45V7BvTP7DZt3iKP-pWEiM4kGd-4d80iiDkX6zGhgUFKEpm7pnD~Mjc7spc8LRIdlIAtRxyr4F20yRauJ7Wy14GfJSkCT4IXu5Z569Eltn66wUb0N9kyomiaxoDSPhZXau6y7p8N~De4bb0Yt7K6OBIJidpAtVRr~Q2Dxe2lGh~FEzX4SzNEdwbdSVs2wLonRpVG5GLr4n6crByLyW4Z6Y309RVyRdEOVJLQ1JLWXFTe6ZOvpERJ3HqblgDPNa3bU3fKbwBvW7g8ShCZ~x-oeyqbya4Pg__&Key-Pair-Id=K2NXBXLF010TJW',
      link: 'https://www.andrea-herzig.de/',
    },
    {
      name: "TeacherMen's Friends",
      location: 'aus 94405 Landau a. d. Isar',
      image: 'https://scontent-muc2-1.xx.fbcdn.net/v/t39.30808-6/293155048_740134597322979_4071837228414404162_n.jpg?_nc_cat=105&ccb=1-7&_nc_sid=a2f6c7&_nc_ohc=2LOzisTJJkoAX8BSx_n&_nc_ht=scontent-muc2-1.xx&oh=00_AfCaCbgOnGx5jtvGN8_MxOueXZtJvK20iVfrc2UAZ9s7Wg&oe=6527F00F',
      link: 'https://www.facebook.com/profile.php?id=100039793366614',
    },
    {
      name: 'Musikschule Temel',
      location: 'aus 94522 Wallersdorf',
      image: 'https://www.musikschule-temel.de/cms/cms/upload/logos/Logo_MusikstudiofrHomepage.jpg',
      link: 'https://www.musikschule-temel.de/cms/cms/front_content.php?idcat=3',
    },
    {
      name: 'Voices',
      location: 'aus 84160 Frontenhausen',
      image: 'https://www.voices-music.com/s/img/emotionheader.png?1513805912.940px.120px',
      link: 'https://www.voices-music.com/',
    },
    {
      name: 'Picantos',
      location: 'aus 94121 Straßkirchen',
      image: '/supporter/picantos.png',
      link: 'https://www.picantos.de/',
    },
    {
      name: 'DJ Reflex',
      location: 'aus 92421 Schwandorf',
      image: 'https://scontent-muc2-1.xx.fbcdn.net/v/t39.30808-6/281231493_5309948829062540_830823864974889683_n.jpg?_nc_cat=102&ccb=1-7&_nc_sid=a2f6c7&_nc_ohc=5mcrZDru5N4AX8zLUF5&_nc_ht=scontent-muc2-1.xx&oh=00_AfCC2X6WIn36PPFURdroFShIrOH3UL-BEo_zXc_K46g96Q&oe=652777A6',
      link: 'https://www.veranstaltungsmanagementreflex.com/',
    },
    {
      name: 'SIXTY-UP',
      location: 'aus 94431 Pilsting',
      image: 'https://www.sixty-up.de/images/headers/BANDLOGO_2012_small.png',
      link: 'https://www.sixty-up.de/',
    },
    {
      name: 'Bischof-Riccabona Mittelschule',
      location: 'aus 94522 Wallersdorf',
      image: 'https://layout.verwaltungsportal.de/1580/img/logo.png',
      link: 'https://www.vswallersdorf.de/',
    },  
  ];